### ISSUE TITLE
Drawing problem

### ISSUE THREAD

**Issue by linsonM** [thuml/Nonstationary_Transformers#11]
Hi author! I want to use this method to my paper, please about how to get Figure 1?
thank your answer！

**Comment by WenWeiTHU** [comment]
Hi, thanks for your interest.

The first column: the original series as training dataset
The second: window-partitioned series as model inputs
The third row: train Transformer with raw inputs/ stationarized inputs(e.g. normalization) / train with NSTransformer, then visualize the learned attention maps

**Comment by linsonM** [comment]
已收到邮件!
