### ISSUE TITLE
dataset size question

### ISSUE THREAD

**Issue by creamiracle** [thuml/Nonstationary_Transformers#13]
Hey, thanks for the impressive work, I just wanna know is this model suit for "daily" time series, for example, some items only have 2 years data(almost 700 timestamps), can this model used on this kind of dataset?
Thanks and hope for reply.

**Comment by WenWeiTHU** [comment]
Of course this kind of deep models can work on data with coarse granularity (e.g. the illness dataset used in our experiment has only 578 training samples).
