### ISSUE TITLE
OT column in datasets

### ISSUE THREAD

**Issue by kashif** [thuml/Nonstationary_Transformers#14]
Hello!

Do you know what the `OT` column in the datsets is? If I understand your experiments correctly, in the "S" case the model gets the `OT` column as the data? Where as I thought the data would be all the individual columns?

Thanks!
Kashif

**Comment by kashif** [comment]
ok so i think i figured it out from the informer code repo...

**Comment by ZhangShaungnj** [comment]
> ok so i think i figured it out from the informer code repo...

Can you explain it for me ？ I am a beginner. Thank you！

**Comment by WenWeiTHU** [comment]
> > ok so i think i figured it out from the informer code repo...
> 
> Can you explain it for me ？ I am a beginner. Thank you！

Hello, you can look at this for a detailed explanation: https://github.com/thuml/Autoformer/issues/97
