### ISSUE TITLE
Multivariate Time Series ADF Test Stat

### ISSUE THREAD

**Issue by xcvil** [thuml/Nonstationary_Transformers#15]
Dear authors,

I am curious how you got the multivariate ADF test stat in your paper, e.g. ETTm2 = -6.225. `arch.unitroot.ADF` is only for univariate.

Thanks!

**Comment by WenWeiTHU** [comment]
Hello, we use the averged adf.stat of each variable to measure the degree of stationarity for multivariate dataset.
