### ISSUE TITLE
standard scalar/fit scaler/transform

### ISSUE THREAD

**Issue by Aimen1996** [thuml/Nonstationary_Transformers#17]
file = data_loader.py
if self.scale:
            train_data = df_data[border1s[0]:border2s[0]]
            self.scaler.fit(train_data.values)
            data = self.scaler.transform(df_data.values)
here why you applied fit scaler to 'train_data' and then applied transform to whole df_data.values. its beyond my understanding.

**Comment by WenWeiTHU** [comment]
Hello, it is a data preprocess convention to scale unseen data (testing set) by observered data statistics (training set) in time series analysis (also in deep learning and ml).
