### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by LY-must-win** [thuml/Nonstationary_Transformers#19]
当我选用ns_Transfomer运行时报出TypeError: 'NoneType' object is not subscriptable这样的错误，但选择Transformer没有这样的问题
![image](https://user-images.githubusercontent.com/103368413/229266927-cf556591-4ab7-4ab3-8064-c098632b39d3.png)
![image](https://user-images.githubusercontent.com/103368413/229266972-598a6e65-cff6-4965-845e-3ef51ee6dea9.png)

**Comment by ZhangShaungnj** [comment]
Hi，did you resolve the problem.If so,can you tell me how to do that.Thank you^_^

**Comment by LY-must-win** [comment]
> Hi，did you resolve the problem.If so,can you tell me how to do that.Thank you^_^

I'm sorry, I don't know what the reason for the mistake is.

**Comment by ZhangShaungnj** [comment]
Fine
