### ISSUE TITLE
dataset中scale参数

### ISSUE THREAD

**Issue by liuweishuo** [thuml/Nonstationary_Transformers#2]
在dataset中不应该做归一化吧 在model的forward中已经做归一化了，如果在之前做了归一化那么进入模型的就是归一化之后的平稳数据，计算出的mean、delta也不是原始数据的了。

**Comment by WenWeiTHU** [comment]
你好，dataset中的scale参数是将训练集整段序列的均值方差用于测试集整段序列的尺度变换，这在时序预测中是一个标准做法，类似CV中用ImageNet的均值方差做Normalization，在整段序列上进行尺度变换操作并不会改变影响序列的平稳性。

由于模型的输入是对整段序列按窗口进行划分获得的，每个窗口有独立的均值方差，不同于对整段序列的尺度变换，我们提出的Series Stationarization独立地在模型输入序列窗口内部进行了归一化，消除了各窗口内的均值方差差异，从而降低了整段序列的非平稳性。

**Comment by kpmokpmo** [comment]
如作者所言，对训练集整段做z-score其子段（窗口）的方差可能差异很大，那么不同特征之间子段的方差一致这一假设似乎不容易满足。
由于以上原因，实际训练的时候我遇到了偶发性的nan值，是由于代码中实现tau的时候用了torch.exp。当原始方差差异较大、且那个小的project网络初始化不够好的话，容易导致exp的溢出。我理解exp的主要作用只是单纯地保证正值，那么姑且用torch.abs或者放弃保证正值，来保证肯定不会出现nan。效果暂时还没跑出来。

**Comment by liuweishuo** [comment]
> 你好，dataset中的scale参数是将训练集整段序列的均值方差用于测试集整段序列的尺度变换，这在时序预测中是一个标准做法，类似CV中用ImageNet的均值方差做Normalization，在整段序列上进行尺度变换操作并不会改变影响序列的平稳性。
> 
> 由于模型的输入是对整段序列按窗口进行划分获得的，每个窗口有独立的均值方差，不同于对整段序列的尺度变换，我们提出的Series Stationarization独立地在模型输入序列窗口内部进行了归一化，消除了各窗口内的均值方差差异，从而降低了整段序列的非平稳性。

你好 感谢回复。如果是在对整个训练集做z-score归一化之后，模型的预测数值也是归一化之后的数值了。代码中是没有将预测数据完全逆归一化为原始数据范围的部分的。也就是计算的mae这些指标也都是在整体归一化之后的数据规模上的计算的。

**Comment by liuweishuo** [comment]
> 如作者所言，对训练集整段做z-score其子段（窗口）的方差可能差异很大，那么不同特征之间子段的方差一致这一假设似乎不容易满足。 由于以上原因，实际训练的时候我遇到了偶发性的nan值，是由于代码中实现tau的时候用了torch.exp。当原始方差差异较大、且那个小的project网络初始化不够好的话，容易导致exp的溢出。我理解exp的主要作用只是单纯地保证正值，那么姑且用torch.abs或者放弃保证正值，来保证肯定不会出现nan。效果暂时还没跑出来。

不同的dataaet(train,vail,test,pred)都采用自己的StandardScaler，不应该是所有的dataset都采用测试集的mean、std吗？特别是pred时候，在真实场景中target肯定是不全的，target和feature的长度不同。

**Comment by liuweishuo** [comment]
> 你好，dataset中的scale参数是将训练集整段序列的均值方差用于测试集整段序列的尺度变换，这在时序预测中是一个标准做法，类似CV中用ImageNet的均值方差做Normalization，在整段序列上进行尺度变换操作并不会改变影响序列的平稳性。
> 
> 由于模型的输入是对整段序列按窗口进行划分获得的，每个窗口有独立的均值方差，不同于对整段序列的尺度变换，我们提出的Series Stationarization独立地在模型输入序列窗口内部进行了归一化，消除了各窗口内的均值方差差异，从而降低了整段序列的非平稳性。

我看到代码里训练集、测试集的归一化是分开进行的，并没有用训练集的mean、std来归一化测试集。

**Comment by WenWeiTHU** [comment]
> > 你好，dataset中的scale参数是将训练集整段序列的均值方差用于测试集整段序列的尺度变换，这在时序预测中是一个标准做法，类似CV中用ImageNet的均值方差做Normalization，在整段序列上进行尺度变换操作并不会改变影响序列的平稳性。
> > 由于模型的输入是对整段序列按窗口进行划分获得的，每个窗口有独立的均值方差，不同于对整段序列的尺度变换，我们提出的Series Stationarization独立地在模型输入序列窗口内部进行了归一化，消除了各窗口内的均值方差差异，从而降低了整段序列的非平稳性。
> 
> 你好 感谢回复。如果是在对整个训练集做z-score归一化之后，模型的预测数值也是归一化之后的数值了。代码中是没有将预测数据完全逆归一化为原始数据范围的部分的。也就是计算的mae这些指标也都是在整体归一化之后的数据规模上的计算的。

你好，这部分可以通过预测后调用inverse_transform类方法返回到原始数据范围。

在实验对比上，所有用来比较的模型都是用同样公平的方式来计算MSE与MAE的，在此基础上我们的方法仍能在各类Transformer上取得一致的提升。另外，这种用整体归一化后的序列比较预测结果的做法是也与目前大多深度模型时序预测的Benchmark相一致的，例如：[FEDformer](https://github.com/DAMO-DI-ML/ICML2022-FEDformer), [Pyraformer](https://github.com/alipay/Pyraformer), [ETSformer](https://github.com/salesforce/ETSformer), [Autoformer](https://github.com/thuml/Autoformer)
