### ISSUE TITLE
可视化效果不佳

### ISSUE THREAD

**Issue by luolundashu** [thuml/Nonstationary_Transformers#20]
> 
![image](https://user-images.githubusercontent.com/95688743/229794514-d30df211-5389-41d1-a803-f1ae5b157f89.png)
请问为什么我在使用etth1 得出的结果如果，mse和论文相似0.3左右，但是可视化时，明显不佳.

**Comment by WenWeiTHU** [comment]
您好，这张图是否为个别样本存在的问题？

我们在Plot结果时，图表的纵坐标范围会选定为单个输入窗口。而MSE是衡量整个测试数据集的预测效果，会和某个单一预测窗口效果存在一定Gap。

**Comment by LY-must-win** [comment]
> 您好，这张图是否为个别样本存在的问题？
> 
> 我们在Plot结果时，图表的纵坐标范围会选定为单个输入窗口。而MSE是衡量整个测试数据集的预测效果，会和某个单一预测窗口效果存在一定Gap。

”图表的纵坐标范围会选定为单个输入窗口“这句话我没太明白，test_result里面预测的不是OT的结果吗？
