### ISSUE TITLE
在data_factory.py中flag==test将drop_last=False是，测试结果显示tuple index out of range

### ISSUE THREAD

**Issue by LY-must-win** [thuml/Nonstationary_Transformers#21]
![image](https://user-images.githubusercontent.com/103368413/230054797-147fabc3-dd0b-4266-97ad-4292fef12071.png)
之前drop_last默认为True并且设置预测长度为1的时候，得出的测试集长度会减少，然后设置drop_last==False时报错了，我想知道原因是什么和解决办法。

**Comment by WenWeiTHU** [comment]
您好，这个错误信息不太清楚，可能是最后一个batch的形状问题？

要避免漏掉测试数据的情况，可以用下图的方式：

<img width="359" alt="image" src="https://user-images.githubusercontent.com/39073236/231088466-69187824-b91e-47f5-8bbf-1fd0cfecbfcb.png">

**Comment by LY-must-win** [comment]
谢谢你的解答，我试一下，我想这个问题大概是划分的测试集数量不能够被batch整除，存在余数的情况，故此设计drop_last为True吧？
&nbsp;


1763050170
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yong ***@***.***&gt;; 
发送时间: 2023年4月11日(星期二) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuml/Nonstationary_Transformers] 在data_factory.py中flag==test将drop_last=False是，测试结果显示tuple index out of range (Issue #21)





 
您好，这个错误信息不太清楚，可能是最后一个batch的形状问题？
 
要避免漏掉测试数据的情况，可以用下图的方式：

**Comment by WenWeiTHU** [comment]
是的，将测试时batch_size设为1可以避免这个问题。

**Comment by LY-must-win** [comment]
好的，我看您文献的结果都是标准化结果的比较，而我运用我的数据集面向实际问题时我把结果反标准化后误差比较大，预测效果也差强人意，特别是多步预测。可能是数据量较小，总的数据是两千多个，我想知道模型应该如何调参使得结果更好




1763050170
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuml/Nonstationary_Transformers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuml/Nonstationary_Transformers] 在data_factory.py中flag==test将drop_last=False是，测试结果显示tuple index out of range (Issue #21)





 
是的，将测试时batch_size设为1可以避免这个问题。
