### ISSUE TITLE
经常报这个错，有人遇到过吗？不知道怎么处理，请大神给解决办法，好像是参数的问题，换别的参数就没问题，不知道问题所在

### ISSUE THREAD

**Issue by hardy110** [thuml/Nonstationary_Transformers#23]
Args in experiment:
Namespace(is_training=1, model_id='test', model='ns_Autoformer', data='custom', root_path='./all_sj/', data_path='dataset.csv', features='MS', target='close', freq='t', checkpoints='./results/checkpoints/', seq_len=131, label_len=70, pred_len=5, enc_in=5, dec_in=5, c_out=1, d_model=752, n_heads=8, e_layers=4, d_layers=2, d_ff=1648, moving_avg=6, factor=1, distil=True, dropout=0.11499999999999999, embed='timeF', activation='softmax', output_attention=True, do_predict=True, num_workers=0, itr=3, train_epochs=10, batch_size=16, patience=3, learning_rate=2.9954351944587492e-05, des='test', loss='sparse_categorical_crossentropy', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1', seed=20, p_hidden_dims=[208, 208, 208], p_hidden_layers=3)
Use GPU: cuda:0
>>>>>>>start training : test_ns_Autoformer_custom_ftMS_sl131_ll70_pl5_dm752_nh8_el4_dl2_df1648_fc1_ebtimeF_dtTrue_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 5452
val 795
test 1592
Traceback (most recent call last):
  File "/tmp/Nonstationary_Transformers/./run_test.py", line 66, in <module>
    exp.train(setting)
  File "/tmp/Nonstationary_Transformers/exp/exp_main.py", line 148, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)[0]
  File "/root/anaconda3_gpu_keras/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/Nonstationary_Transformers/ns_models/ns_Autoformer.py", line 127, in forward
    seasonal_init, trend_init = self.decomp(x_enc)
  File "/root/anaconda3_gpu_keras/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/Nonstationary_Transformers/ns_layers/Autoformer_EncDec.py", line 49, in forward
    res = x - moving_mean
RuntimeError: The size of tensor a (131) must match the size of tensor b (130) at non-singleton dimension 1

**Comment by hardy110** [comment]
排查下来是这个class导致了 数据的shape变少了
class moving_avg(nn.Module):
    """
    Moving average block to highlight the trend of time series
    """
    def __init__(self, kernel_size, stride):
        super(moving_avg, self).__init__()
        self.kernel_size = kernel_size
        self.avg = nn.AvgPool1d(kernel_size=kernel_size, stride=stride, padding=0)

    def forward(self, x):
        print(x.shape)
        # padding on the both ends of time series
        front = x[:, 0:1, :].repeat(1, (self.kernel_size - 1) // 2, 1)
        end = x[:, -1:, :].repeat(1, (self.kernel_size - 1) // 2, 1)
        x = torch.cat([front, x, end], dim=1)
        x = self.avg(x.permute(0, 2, 1))
        x = x.permute(0, 2, 1)
        print(x.shape)
        return x

**Comment by WenWeiTHU** [comment]
> 排查下来是这个class导致了 数据的shape变少了 class moving_avg(nn.Module): """ Moving average block to highlight the trend of time series """ def **init**(self, kernel_size, stride): super(moving_avg, self).**init**() self.kernel_size = kernel_size self.avg = nn.AvgPool1d(kernel_size=kernel_size, stride=stride, padding=0)
> 
> ```
> def forward(self, x):
>     print(x.shape)
>     # padding on the both ends of time series
>     front = x[:, 0:1, :].repeat(1, (self.kernel_size - 1) // 2, 1)
>     end = x[:, -1:, :].repeat(1, (self.kernel_size - 1) // 2, 1)
>     x = torch.cat([front, x, end], dim=1)
>     x = self.avg(x.permute(0, 2, 1))
>     x = x.permute(0, 2, 1)
>     print(x.shape)
>     return x
> ```

这边应该是模型默认kernel_size为奇数；为偶数时，line4-5改成self.kernel_size// 2就可以了
