### ISSUE TITLE
real_pred和pred

### ISSUE THREAD

**Issue by libeiheng** [thuml/Nonstationary_Transformers#27]
real_prediction.npy
pred.npy

在咱们这个模型里,最后预测结果取上面那个值合适,多谢.

**Comment by WenWeiTHU** [comment]
您好，感谢关注。这里两个预测结果应该没有差别，前者是通过 exp.pred 得到，可以查看相应的数据集类 Dataset_Pred的实现。如果您需要得到对在原始数据集上的预测值，因为在数据处理过程中进行了对训练测试集的归一化（模型输入为原始数据集的归一化值），还需调用这个类的 inverse_transform方法。
