### ISSUE TITLE
如何构建自己的数据集

### ISSUE THREAD

**Issue by xiao-song2022** [thuml/Nonstationary_Transformers#29]
老师您好，我读了您的文章，觉得idea非常好，一定程度上解决了非平稳序列的问题，于是我想在金融汇率数据进行实证，但是在写data_loader.py类时，不太清楚您怎么构造的数据集，所以向您求助，如果您方便的话，可以麻烦您在data_loader.py类更新一些注释，或者在github上进行一些提示吗？十分感谢！

**Comment by WenWeiTHU** [comment]
您好，感谢关注！本repo主要考虑nsformer实现，关于构建自己的数据集，这里有一些相关的issue可供参考，希望有所帮助：
https://github.com/thuml/Time-Series-Library/issues/18
https://github.com/thuml/Autoformer/issues/143
https://github.com/thuml/Time-Series-Library/issues/43

**Comment by xiao-song2022** [comment]
感谢您的回复！我已经成功构建数据类（虽然有可能错误）。并且在我的数据集上复现的NS-Transtormer的性能超过Transformer的LSTM等其他时序模型
