### ISSUE TITLE
关于tau和delta的计算

### ISSUE THREAD

**Issue by MagicXY** [thuml/Nonstationary_Transformers#3]
![image](https://user-images.githubusercontent.com/14818170/197391219-38fa3b05-3771-4543-b9ba-e74ab7ff88f4.png)
谢谢你们的工作，有一个疑问，为什么tau 和 delta的计算可以表示为以上的MLP映射？谢谢

**Comment by WenWeiTHU** [comment]
> ![image](https://user-images.githubusercontent.com/14818170/197391219-38fa3b05-3771-4543-b9ba-e74ab7ff88f4.png) 谢谢你们的工作，有一个疑问，为什么tau 和 delta的计算可以表示为以上的MLP映射？谢谢

你好，感谢关注，因为在这个推导中我们用到了部分层的线性假设，因为非线性激活函数的存在，这个假设实际上是很难严格满足的。但是通过推导可以看出，拟合原来attention map的关键在于引入对pre-softmax score的行平移和尺度变化因子，而且这个因子与未平稳化序列的统计量有显著关联的（例如\tau与\sigma_x）。所以为了弱化线性条件和适应其他Transformer的attention机制，我们用了一个比较简单的mlp projector，希望从整个未平稳化序列的数据集中学习这两个因子。
