### ISSUE TITLE
这里的步长是什么意思呀？

### ISSUE THREAD

**Issue by wjli-debug** [thuml/Nonstationary_Transformers#30]
![image](https://github.com/thuml/Nonstationary_Transformers/assets/116251731/15f6e7a7-73ab-4527-9a43-9fa8094707e4)
作者你好，我看到你的代码对于非平稳时序数据效果很好，但是在这三个参数中有一点疑惑，label_len = 48是什么意思呀？观测数据不是96，然后基于96行观测数据预测未来96个时点的数据吗？

**Comment by WenWeiTHU** [comment]
是的，seq_len和pred_len确定了预测数据的输入输出长度。label_len参数可参考[informer论文](https://ojs.aaai.org/index.php/AAAI/article/view/17325/17132)以及https://github.com/thuml/Time-Series-Library/issues/49
