### ISSUE TITLE
patch

### ISSUE THREAD

**Issue by ynning** [thuml/Nonstationary_Transformers#36]
您的序列平稳化和revin有什么区别尼？

**Comment by WenWeiTHU** [comment]
Hello, it has be emphasized in the paper. 

<img width="1232" alt="图片" src="https://github.com/thuml/Nonstationary_Transformers/assets/39073236/704ce94b-ccab-4716-8144-5349672404e6">

**Comment by ynning** [comment]
> Hello, it has be emphasized in the paper.
> 
> <img alt="图片" width="1232" src="https://private-user-images.githubusercontent.com/39073236/310714735-704ce94b-ccab-4716-8144-5349672404e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzU3MDYsIm5iZiI6MTcwOTc3NTQwNiwicGF0aCI6Ii8zOTA3MzIzNi8zMTA3MTQ3MzUtNzA0Y2U5NGItY2NhYi00NzE2LTgxNDQtNTM0OTY3MjQwNGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxMzY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNzc4YTljZGM3ODUxZWQxYWYwYjcwYzcyY2I1NGU2ZThmZDg5ZWFiZWM5MjM1MzFhMjdiMGViOWFlYzZhNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RezRaeF_ee186L4vYIvPBGLjbesWwYD_eRigCuP_msU">

**Comment by ynning** [comment]
那 请问如果我要在你的序列归一化之后加patchtst里面的patch操作，我可以在计算多头自注意力的时候，直接把您的去平稳化注意替换掉原始注意力吗？维度需要改变吗？
