### ISSUE TITLE
关于非平稳的问题

### ISSUE THREAD

**Issue by ownnaruto** [thuml/Nonstationary_Transformers#37]
您好，我对于时间序列非平稳带来的问题一直存在一些疑惑，时间序列非平稳是指序列的统计信息随时间变化，可是这到底是如何影响神经网络模型的预测呢？神经网络预测输入的是历史序列，输出的是未来序列，只要这个映射关系是存在一定规律的，那么神经网络应该就能够在一定程度上学到这种关系，序列的非平稳是如何影响这种映射关系的呢？为什么平稳的序列就一定更好呢？（白噪声也是一种平稳序列，可是却完全无法预测。

**Comment by WenWeiTHU** [comment]
您好，感谢关注，问题的关键的是非平稳性带来的时变分布对深度网络的泛化性是不好的（例如测试时出现了训练时完全未见过的时序变化）。平稳化方法对深度模型时有效的主要原因也是在一定程度缓解了训练和测试时的分布差异。但是正如你所说的白噪声作为一种平稳序列，却完全无法预测。平稳化方法其实也导致序列用用于预测的信息减少了，所以深度网络的输出产生了过平稳现象，这也正是我们的文章要解决的核心问题。
