### ISSUE TITLE
Ablation with Stat + DeFF + DeAttn

### ISSUE THREAD

**Issue by rouniuyizu** [thuml/Nonstationary_Transformers#38]
Thank you for publishing code!

I have a question on the following table, and would be great if you could enlighten me on this: given the fact that when combining Stat with either DeFF/DeAtten, performance gets boosted, have you tried to benchmark the case where all three are applied, i.e. Stat + DeFF + DeAttn? 

Also for DeFF implementation, how exactly should it be coded? 

![image](https://github.com/thuml/Nonstationary_Transformers/assets/7133753/76c8e62e-457d-4cf0-af26-0f3082e95b48)

**Comment by WenWeiTHU** [comment]
Hi, you can refer our response to Reviewer PhZA (Part 2) on https://openreview.net/forum?id=ucNDIDRNjjv
