### ISSUE TITLE
How to calculate the stationarity of the output

### ISSUE THREAD

**Issue by isCopyman** [thuml/Nonstationary_Transformers#39]
![image](https://github.com/thuml/Nonstationary_Transformers/assets/25970108/fa8790f2-2c6b-4929-a08b-2134452fc754)
In this discussion, it is mentioned that all the predicted time series are arranged in chronological order and then compared with the ground truth in terms of stationarity, which results in the following figure:
![image](https://github.com/thuml/Nonstationary_Transformers/assets/25970108/db22bffc-32a9-4481-a45c-db721a476167)
Could you please explain specifically how the predicted time series are arranged? Assume the length of the test sequence is from t1 to t10, and we have prediction sequences y1=[t1,t2,t3] and y2=[t2,t3,t4]. How do we handle the overlap between y1 and y2 in such cases?"

**Comment by WenWeiTHU** [comment]
Hello, we compute the degree of stationarity on each windowed time series and report the averaged scroe
