### ISSUE TITLE
Autoformer Implementation

### ISSUE THREAD

**Issue by omerlux** [thuml/Nonstationary_Transformers#4]
First, thanks for such a great work.
I saw that actually the **ns_Autoformer** model does not use the `tau` and `delta` - will the code will be updated?
In addition, I have a question about the following line:
https://github.com/thuml/Nonstationary_Transformers/blob/2f53d988ab8bdf9261f6e614332ff5bc2580a05f/ns_layers/AutoCorrelation.py#L118
In the **cross** autocorrelation layer, the keys and values (originated from the encoder) are padded with zeros for the FFT process and multiplication. Thus there is no way to use the `delta` again (as you guys mentioned in the self-attention of the Transformer's decoder) because it will be `seq_len` size in comparison to the `corr` size, which is `label_len + pred_len`.
How did you solve this issue?

Thanks!

**Comment by WenWeiTHU** [comment]
Thank you for your correction! It seems we omit them in the `ns_Autoformer` model, we will fix it soon.

For the question about the `delta` and `corr` size mismatch, we have mentioned how we solve it in Appendix E.2 of our paper: for the row length of attention score differs from S × S, where S is the initial input sequence length, we omit the shifting de-stationary factor by setting it as 0-vector. In our ablation D.2, the performance will not degrade a lot without `delta`. In the code implementation, setting `delta=None` in cross-attn is okay.
