### ISSUE TITLE
Visualization code

### ISSUE THREAD

**Issue by Zero-coder** [thuml/Nonstationary_Transformers#5]
First,thank you very much for providing such insight for tsf work
and could you please  share the visualization code for adf-test code and prediction plot code.

**Comment by WenWeiTHU** [comment]
> First,thank you very much for providing such insight for tsf work and could you please share the visualization code for adf-test code and prediction plot code.

Hello, we use the returned `adf.stat` of `arch.unitroot.ADF` to measure the degree of stationarity in our paper [(ref)](https://arch.readthedocs.io/en/latest/unitroot/generated/arch.unitroot.ADF.html). And prediction plots are all visualizations of the series predictions for the first variable on the ETTm2 dataset。

**Comment by Zero-coder** [comment]
Thanks for your responding,it's helpful,and I want to have a discuss about my recent work,is there any way I can contact you?
