### ISSUE TITLE
ETTm2 scripts

### ISSUE THREAD

**Issue by zahraatashgahi** [thuml/Nonstationary_Transformers#7]
Hi, I’m trying to run the experiments on ETTm2. I found in this repository the scripts for ETTh2. Are you using the same settings for ETTm2? If not, would you please add the scripts for ETTm2?

**Comment by WenWeiTHU** [comment]
Hi, thanks for your interest.

We use the same forecasting setting on ETT datasets. You can change the data_path to ETTm2 directly, and tune `p_hidden_dims` and `p_hidden_layers` for different models.
